name: 'Z-Wave Sensor Frank'
packageKey: 'zwave-sensor'
permissions:
  zwave: {}
description: "SmartThings driver for Z-Wave sensor devices"
vendorSupportInformation: "https://support.smartthings.com"
